global using static Bot.StartupTasks.LoadWhiteListBlackList;
global using static Bot.StartupTasks.LoadInMemorySettings;
global using static Bot.StartupTasks.MainClientSetup;
global using static Bot.StartupTasks.AnonClientSetup;
global using static Bot.StartupTasks.ChannelsSetup;
global using static Bot.StartupTasks.LoadModules;
global using static Bot.StartupTasks.NpgsqlSetup;
global using static Bot.StartupTasks.LoadConfig;
global using static Bot.StartupTasks.RedisSetup;
global using static Bot.Utils.GlobalHelpers;
global using static Bot.Services.PubSub;
global using static Bot.Services.Helix;
global using static Serilog.Log;
global using Serilog;
global using Dapper;
global using OneOf;