global using static Bot.Workflows.LoadWhiteListBlackList;
global using static Bot.Workflows.LoadInMemorySettings;
global using static Bot.Workflows.MainClientSetup;
global using static Bot.Workflows.AnonClientSetup;
global using static Bot.Workflows.ChannelsSetup;
global using static Bot.Workflows.LoadModules;
global using static Bot.Workflows.NpgsqlSetup;
global using static Bot.Workflows.LoadConfig;
global using static Bot.Workflows.RedisSetup;
global using static Bot.Utils.GlobalHelpers;
global using static Bot.Services.PubSub;
global using static Bot.Services.Helix;
global using static Serilog.Log;
global using Serilog;
global using Dapper;
global using OneOf;